# Generated by Django 4.1.5 on 2024-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
