name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry==1.6.1

      - name: Validate the structure of the pyproject.toml
        run: poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install

      - name: Check code formatting by black
        run: poetry run black . --check

      - name: Lint code by flake8
        run: poetry run flake8 .

      - name: Check types by mypy
        run: poetry run mypy .